openapi: "3.0.2"
info:
  title: SimpleMessager REST API
  version: "1.0"
servers:
  - url: https://localhost/v1
tags:
  - name: account
    description: Учётная запись
  - name: user
    description: Пользователи
  - name: chatroom
    description: Чат-комнаты
  - name: message
    description: Сообщения
paths:
  /account/singin:
    post:
      tags:
        - account
      summary: Вход в аккаунт
      parameters:
        - $ref: "#/components/parameters/username_required"
        - $ref: "#/components/parameters/password"
      responses:
        "200":
          description: Вход успешно произведён
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthToken"
        "400":
          $ref: "#/components/responses/RequiredParameterNotSpecified"
        "403":
          description: Учётные данные не найдены
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /account/singout:
    post:
      tags:
        - account
      summary: Выход из аккаунта
      parameters:
        - $ref: "#/components/parameters/token"
      responses:
        "200":
          description: Выход успешно произведён
        "401":
          $ref: "#/components/responses/InvalidTokenSpecified"

  /account/singup:
    post:
      tags:
        - account
      summary: Регистрация аккаунта
      parameters:
        - $ref: "#/components/parameters/username_required"
        - $ref: "#/components/parameters/surname_required"
        - $ref: "#/components/parameters/name_required"
      responses:
        "201":
          description: Пользователь успешно зарегистрирован
        "400":
          $ref: "#/components/responses/RequiredParameterNotSpecified"
        "403":
          description: Пользователь с таким псевдонимом уже существует
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /users:
    get:
      tags:
        - user
      summary: Список пользователей
      parameters:
        - $ref: "#/components/parameters/token"
        - $ref: "#/components/parameters/count_per_page"
        - $ref: "#/components/parameters/page_number"
        - $ref: "#/components/parameters/filter_username"
        - $ref: "#/components/parameters/filter_surname"
        - $ref: "#/components/parameters/filter_name"
      responses:
        "200":
          description: Список пользователей
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/User"
        "401":
          $ref: "#/components/responses/TokenNotSpecified"
        "403":
          $ref: "#/components/responses/InvalidTokenSpecified"

  /users/{userId}:
    get:
      tags:
        - user
      summary: Информация о пользователе
      parameters:
        - $ref: "#/components/parameters/userId"
        - $ref: "#/components/parameters/token"
      responses:
        "200":
          description: Информация о пользователе
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "401":
          $ref: "#/components/responses/TokenNotSpecified"
        "403":
          $ref: "#/components/responses/InvalidTokenSpecified"
        "404":
          $ref: "#/components/responses/NotFound"

  /users/{userId}/rooms:
    get:
      tags:
        - user
      summary: Информация о чат-комнатах, в которых состоит пользователь
      parameters:
        - $ref: "#/components/parameters/userId"
        - $ref: "#/components/parameters/token"
      responses:
        "200":
          description: Список чат-комнатах, в которых состоит пользователь
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Chatroom"
        "401":
          $ref: "#/components/responses/TokenNotSpecified"
        "403":
          $ref: "#/components/responses/InvalidTokenSpecified"
        "404":
          $ref: "#/components/responses/NotFound"

  /users/me:
    get:
      tags:
        - user
      summary: Информация о своём аккаунте
      parameters:
        - $ref: "#/components/parameters/token"
      responses:
        "200":
          description: Информация о своём аккаунте
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "401":
          $ref: "#/components/responses/TokenNotSpecified"
        "403":
          $ref: "#/components/responses/InvalidTokenSpecified"

    put:
      tags:
        - user
      summary: Обновление информации о своём аккаунте
      description: Хотя бы один из параметров `username`, `surname` или `name` должен быть указан
      parameters:
        - $ref: "#/components/parameters/token"
        - $ref: "#/components/parameters/username"
        - $ref: "#/components/parameters/surname"
        - $ref: "#/components/parameters/name"
      responses:
        "200":
          description: Информация о текущем пользователе
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        "401":
          $ref: "#/components/responses/TokenNotSpecified"
        "403":
          $ref: "#/components/responses/InvalidTokenSpecified"

  /users/me/rooms:
    get:
      tags:
        - user
      summary: Информация о чат-комнатах, в которых состоит пользователь
      parameters:
        - $ref: "#/components/parameters/token"
      responses:
        "200":
          description: Список чат-комнатах, в которых состоит пользователь
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Chatroom"
        "401":
          $ref: "#/components/responses/TokenNotSpecified"
        "403":
          $ref: "#/components/responses/InvalidTokenSpecified"
        "404":
          $ref: "#/components/responses/NotFound"

  /rooms:
    get:
      tags:
        - chatroom
      summary: Список чат-комнат
      parameters:
        - $ref: "#/components/parameters/token"
        - $ref: "#/components/parameters/count_per_page"
        - $ref: "#/components/parameters/page_number"
        - $ref: "#/components/parameters/filter_title"
        - $ref: "#/components/parameters/filter_private"
        - $ref: "#/components/parameters/filter_adminId"
      responses:
        "200":
          description: Список чат-комнат
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Chatroom"
        "401":
          $ref: "#/components/responses/TokenNotSpecified"
        "403":
          $ref: "#/components/responses/InvalidTokenSpecified"
    post:
      tags:
        - chatroom
      summary: Создать чат-комнату
      parameters:
        - $ref: "#/components/parameters/token"
        - $ref: "#/components/parameters/title"
        - $ref: "#/components/parameters/private"
      responses:
        "200":
          description: Чат-комната успешно создана
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Chatroom"
        "401":
          $ref: "#/components/responses/TokenNotSpecified"
        "403":
          $ref: "#/components/responses/InvalidTokenSpecified"

  /rooms/{roomId}:
    get:
      tags:
        - chatroom
      summary: Информация о чат-комнате
      parameters:
        - $ref: "#/components/parameters/roomId"
        - $ref: "#/components/parameters/token"
      responses:
        "200":
          description: Информация о чат-комнате с указанным
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Chatroom"
        "401":
          $ref: "#/components/responses/TokenNotSpecified"
        "403":
          $ref: "#/components/responses/InvalidTokenSpecified"
        "404":
          $ref: "#/components/responses/NotFound"
    put:
      tags:
        - chatroom
      summary: Обновить чат-комнату
      description: Хотя бы один из параметров `title`, `private` или `adminId` должен быть указан
      parameters:
        - $ref: "#/components/parameters/roomId"
        - $ref: "#/components/parameters/token"

        - $ref: "#/components/parameters/title"
        - $ref: "#/components/parameters/private"
        - $ref: "#/components/parameters/adminId"
      responses:
        "200":
          description: Чат-комната успешно обновлена
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Chatroom"
        "401":
          $ref: "#/components/responses/TokenNotSpecified"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"

  /rooms/{roomId}/invite/{userId}:
    post:
      tags:
        - chatroom
      summary: Пригласить пользователя в чат-комнату
      parameters:
        - $ref: "#/components/parameters/roomId"
        - $ref: "#/components/parameters/userId"
        - $ref: "#/components/parameters/token"
      responses:
        "200":
          description: Приглашение отправлено
        "401":
          $ref: "#/components/responses/TokenNotSpecified"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
    delete:
      tags:
        - chatroom
      summary: Удалить приглашение в чат-комнату
      parameters:
        - $ref: "#/components/parameters/roomId"
        - $ref: "#/components/parameters/userId"
        - $ref: "#/components/parameters/token"
      responses:
        "200":
          description: Приглашение успешно удалено/отклонено
        "401":
          $ref: "#/components/responses/TokenNotSpecified"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"

  /rooms/{roomId}/join:
    post:
      tags:
        - chatroom
      summary: Присоединиться к чат-комнате
      parameters:
        - $ref: "#/components/parameters/roomId"
        - $ref: "#/components/parameters/token"
      responses:
        "200":
          description: Пользователь успешно присоединился к чат-комнате
        "401":
          $ref: "#/components/responses/TokenNotSpecified"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"

  /rooms/{roomId}/leave:
    post:
      tags:
        - chatroom
      summary: Покинуть чат-комнату
      parameters:
        - $ref: "#/components/parameters/roomId"
        - $ref: "#/components/parameters/token"
      responses:
        "200":
          description: Пользователь успешно покинул чат-комнату
        "401":
          $ref: "#/components/responses/TokenNotSpecified"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"

  /rooms/{roomId}/kick/{userId}:
    post:
      tags:
        - chatroom
      summary: Выгнать пользователя из чат-комнаты
      parameters:
        - $ref: "#/components/parameters/roomId"
        - $ref: "#/components/parameters/userId"
        - $ref: "#/components/parameters/token"
      responses:
        "200":
          description: Пользователь был изгнан из чат-комнаты
        "401":
          $ref: "#/components/responses/TokenNotSpecified"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"

  /rooms/{roomId}/messages:
    get:
      tags:
        - message
      summary: Получить сообщения чат-комнаты
      parameters:
        - $ref: "#/components/parameters/roomId"
        - $ref: "#/components/parameters/token"

        - $ref: "#/components/parameters/count_per_page"
        - $ref: "#/components/parameters/page_number"
        - $ref: "#/components/parameters/filter_userId"
        - $ref: "#/components/parameters/filter_type"

      responses:
        "200":
          description: Список сообщений чат-комнаты
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Message"
        "401":
          $ref: "#/components/responses/TokenNotSpecified"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
    post:
      tags:
        - message
      summary: Отправка сообщения в чат-комнату
      parameters:
        - $ref: "#/components/parameters/roomId"
        - $ref: "#/components/parameters/token"
        - $ref: "#/components/parameters/type"
        - $ref: "#/components/parameters/content"
      responses:
        "200":
          description: Сообщение отправлено
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NewMessage"
        "401":
          $ref: "#/components/responses/TokenNotSpecified"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "413":
          $ref: "#/components/responses/TooLarge"
        "415":
          $ref: "#/components/responses/UnsupportedMediaType"

  /rooms/{roomId}/messages/{messageId}:
    put:
      tags:
        - message
      summary: Изменить сообщение
      parameters:
        - $ref: "#/components/parameters/roomId"
        - $ref: "#/components/parameters/messageId"
        - $ref: "#/components/parameters/token"
        - $ref: "#/components/parameters/content"
      responses:
        "200":
          description: Сообщение изменено
        "401":
          $ref: "#/components/responses/TokenNotSpecified"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"
        "413":
          $ref: "#/components/responses/TooLarge"
    delete:
      tags:
        - message
      summary: Удалить сообщение
      parameters:
        - $ref: "#/components/parameters/roomId"
        - $ref: "#/components/parameters/messageId"
        - $ref: "#/components/parameters/token"
      responses:
        "200":
          description: Сообщение удалено
        "401":
          $ref: "#/components/responses/TokenNotSpecified"
        "403":
          $ref: "#/components/responses/Forbidden"
        "404":
          $ref: "#/components/responses/NotFound"

components:
  schemas:
    $ref: "./components/schemas/_index.yaml"

  responses:
    $ref: "./components/responses/_index.yaml"

  parameters:
    $ref: "./components/parameters/_index.yaml"